Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1271, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1099, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1522, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'client_id' into field. Choices are: company_name, contract, date_created, date_updated, email, event, first_name, id, landline, last_name, mobile, sales_contact, sales_contact_id
"GET /clients/?search=Vision HTTP/1.1" 500 159762
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1271, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1099, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1522, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'client_name' into field. Choices are: company_name, contract, date_created, date_updated, email, event, first_name, id, landline, last_name, mobile, sales_contact, sales_contact_id
"GET /clients/?search=Vision HTTP/1.1" 500 160400
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1271, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1099, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1522, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'company' into field. Choices are: company_name, contract, date_created, date_updated, email, event, first_name, id, landline, last_name, mobile, sales_contact, sales_contact_id
"GET /clients/?search=Vision HTTP/1.1" 500 160355
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1329, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1171, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /clients/?search=Vision HTTP/1.1" 500 156995
Internal Server Error: /contracts/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1329, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1171, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /contracts/?search=sales_guy HTTP/1.1" 500 154981
Internal Server Error: /contracts/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1329, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1171, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /contracts/?search=2 HTTP/1.1" 500 154733
Internal Server Error: /contracts/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1329, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1171, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /contracts/?search=2 HTTP/1.1" 500 154596
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1329, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1171, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /users/?search=Admin HTTP/1.1" 500 157341
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1252, in build_filter
    return self._add_q(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1329, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\Harris\Desktop\Formation crap\P12\epic_events\env\lib\site-packages\django\db\models\sql\query.py", line 1171, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /users/?search=management HTTP/1.1" 500 154849
